services :
  mariadb :
    build : ./requirements/mariadb
    container_name : mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks : 
      - inception
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env


networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt