services :
  mariadb :
    image: mariadb:img
    build : ./requirements/mariadb
    container_name : mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks : 
      - inception
    secrets:
      - db_password
      - db_root_password
    env_file:
      - .env

  wordpress :
    image: wordpress:img
    build : ./requirements/wordpress/
    container_name : wordpress
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks : 
      - inception
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password
    env_file:
      - .env
    depends_on:
      - mariadb

  nginx :
    image: nginx:img
    build : ./requirements/nginx/
    container_name : nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks : 
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"

  website :
    image: webiste:img
    build : ./requirements/bonus/website/
    container_name : website
    restart: on-failure
    networks : 
      - inception
    env_file:
      - .env
    ports:
      - "8080:8080"
      
  redis :
    image: redis:img
    build : ./requirements/bonus/redis/
    container_name : redis
    restart: on-failure
    networks : 
      - inception
    depends_on:
      - wordpress

  ftp :
    image: ftp:img
    build : ./requirements/bonus/ftp/
    container_name : ftp
    restart: on-failure
    volumes:
      - wordpress:/var/www/html
    networks : 
      - inception
    secrets:
      - ftp_password
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    depends_on:
      - wordpress

  adminer :
    image: adminer:img
    build : ./requirements/bonus/adminer/
    container_name : adminer
    restart: on-failure
    networks : 
      - inception
    depends_on:
      - mariadb
    ports:
      - "8050:8080"


  portainer:
    image: portainer:img
    build: ./requirements/bonus/portainer
    container_name: portainer
    restart: on-failure
    networks : 
      - inception
    ports:
    - "9443:9443"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/credentials.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt