services :
  mariadb :
    build : ./requirements/mariadb
    image : mariadb
    container_name : mariadb
    restart: on-failure
    volumes:
      - mariadb:/var/lib/mysql
    networks : 
      - inception


networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sel-hime/data/
